name: Leafgit Release

on:
  pull_request:
    types: [closed]
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-version:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.check_version.outputs.new_version }}
      is-releasing: ${{ steps.check_label.outputs.is-releasing }}
      check-passed: ${{ steps.check_version.outcome }}

    steps:
      - uses: actions/checkout@v4
      - name: Check skip-release label
        id: check_label
        run: |
          if [[ "${{ github.event.pull_request.labels[*] }}" == *"skip-release"* ]]; then
            echo "is-releasing=false" >> $GITHUB_OUTPUT
          else
            echo "is-releasing=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Check version
        id: check_version
        run: |
          pip install packaging
          python .github/scripts/check_version.py
        env:
          SKIP_RELEASE: ${{ steps.check_label.outputs.is-releasing }}

  notify-error:
    needs: check-version
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number:  context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `バージョンチェックが失敗しました\n\n[ワークフロー実行を確認](${context.payload.repository.html_url}/actions/runs/${context.runId})`
            })

  build:
    needs: check-version
    if: needs.check-version.outputs.is-releasing == 'true'
    uses: ./.github/workflows/build.yaml

  release:
    needs: [check-version, build]
    if: needs.check-version.outputs.is-releasing == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      
      - name: Create release assets
        env:
          VERSION: ${{ needs.check-version.outputs.version }}
        run: |
          mkdir release-assets
          mv artifacts/leafgit-linux/leafgit release-assets/leafgit-linux-$VERSION-x86_64
          mv artifacts/leafgit-windows/leafgit.exe release-assets/leafgit-windows-$VERSION-x86_64.exe
          chmod +x release-assets/leafgit-linux-$VERSION-x86_64

      - name: Create Git tag
        env:
          VERSION: ${{ needs.check-version.outputs.version }}
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a "v$VERSION" -m "Release v$VERSION"
          git push origin "v$VERSION"

      - name: Create release note
        id: create_release_note
        run: |
          TEMPLATE=$(cat .github/releasenote_template.md)
          TEMPLATE=${TEMPLATE//\{VERSION\}/${GITHUB_REF_NAME}}

          echo "RELEASE_BODY<<EOF" >> $GITHUB_OUTPUT
          echo "$TEMPLATE" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create release page
        uses: softprops/action-gh-release@v1
        with:
          files: release-assets/*
          draft: true
          prerelease: false
          generate_release_notes: true
          body: ${{ steps.create_release_note.outputs.RELEASE_BODY }}
      